add OneCylinder

diff --git a/machines_list/OLCF/nrsqsub_frontier b/machines_list/OLCF/nrsqsub_frontier
--- a/machines_list/OLCF/nrsqsub_frontier
+++ b/machines_list/OLCF/nrsqsub_frontier
@@ -69,21 +69,31 @@ if [ ! -f $bin ]; then
   exit 1
 fi
 
-if [ ! $isneknek == 0 ]; then
-if [ ! -f $case.par ]; then
-  echo "Cannot find" $case.par
-  exit 1
-fi
-
-if [ ! -f $case.udf ]; then
-  echo "Cannot find" $case.udf
-  exit 1
-fi
-
-if [ ! -f $case.re2 ]; then
-  echo "Cannot find" $case.re2
-  exit 1
-fi
+if [ ! $isneknek -eq 0 ]; then
+  if [ ! -f $case.par ]; then
+    echo "Cannot find" $case.par
+    exit 1
+  fi
+  
+  if [ ! -f $case.udf ]; then
+    echo "Cannot find" $case.udf
+    exit 1
+  fi
+  
+  if [ ! -f $case.re2 ]; then
+    echo "Cannot find" $case.re2
+    exit 1
+  fi
+else # chk for neknek
+  if [ ! -f $case ]; then
+    echo "Cannot find" $case
+    exit 1
+  fi
+  ntasks_nn=`cat $case | awk -F ':' '{sum+=$2} END{print sum}'`
+  if [ $ntasks -ne $ntasks_nn ]; then
+    echo "Warning: #ranks in $case not matched with $ntasks"
+    exit 1
+  fi
 fi
 
 striping_unit=16777216
@@ -177,7 +187,7 @@ echo "ls -ltra $NVME_HOME" >> $SFILE
 echo "ls -ltra $bin_nvme_libs" >> $SFILE
 echo "ldd $bin_nvme" >> $SFILE
 
-if [ $NEKRS_SKIP_BUILD_ONLY -eq 0 ]; then
+if [ $NEKRS_SKIP_BUILD_ONLY -eq 0 ]; then # TODO: neknek
 echo "# precompilation" >>$SFILE
 echo "srun -N 1 -n 1 $bin_nvme --backend $backend --device-id 0 --setup $case $cimode --build-only $ntasks" >>$SFILE
 echo "if [ \$? -ne 0 ]; then" >> $SFILE
